name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get Nuget Packages
        run: dotnet nuget add source https://nuget.pkg.github.com/JonathanMcCaffrey/index.json --name github --username JonathanMcCaffrey --password ${{ secrets.NUGET_READONLY_KEY }} --store-password-in-clear-text 
      - name: Restore
        run: dotnet restore Client/Client.csproj
      - name: Build
        run: dotnet build Client/Client.csproj --no-restore
      - name: Publish
        run: dotnet publish Client/Client.csproj --no-build --output "Output"
      - name: Test 5
        run: ls Output
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SEA_0411E1010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Output/wwwroot"
          api_location: ""
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SEA_0411E1010 }}
          action: "close"
